/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koperasi;

import Attendance.Today;
import Auth.Login;
import Auth.Session;
import Employees.ReadEmployees;
import Entries.ReadEntries;
import Exits.ReadExits;
import Products.ReadProducts;
import Transaction.Types.ReadTransactionTypes;
import Transactions.Form;
import javax.swing.JOptionPane;

/**
 *
 * @author ryans
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        if(Session.getRole() == null) {
            JOptionPane.showMessageDialog(null, "Silahkan login terlebih dahulu"); 
            Login login = new Login();
            dispose();
            login.setVisible(true);
        } else {
            initComponents();
            setLocationRelativeTo(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuProducts = new javax.swing.JMenuItem();
        menuEmployees = new javax.swing.JMenuItem();
        menuTransactionTypes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuTransactions = new javax.swing.JMenuItem();
        menuEntries = new javax.swing.JMenuItem();
        menuExits = new javax.swing.JMenuItem();
        menuAttendances = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Master");

        menuProducts.setText("Produk");
        menuProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProductsMouseClicked(evt);
            }
        });
        menuProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductsActionPerformed(evt);
            }
        });
        jMenu3.add(menuProducts);

        menuEmployees.setText("Pegawai");
        menuEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmployeesActionPerformed(evt);
            }
        });
        jMenu3.add(menuEmployees);

        menuTransactionTypes.setText("Tipe Transaksi");
        menuTransactionTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransactionTypesActionPerformed(evt);
            }
        });
        jMenu3.add(menuTransactionTypes);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Transaksi");

        menuTransactions.setText("Pembelian");
        menuTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransactionsActionPerformed(evt);
            }
        });
        jMenu4.add(menuTransactions);

        menuEntries.setText("Barang Masuk");
        menuEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntriesActionPerformed(evt);
            }
        });
        jMenu4.add(menuEntries);

        menuExits.setText("Barang Keluar");
        menuExits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitsActionPerformed(evt);
            }
        });
        jMenu4.add(menuExits);

        jMenuBar2.add(jMenu4);

        menuAttendances.setText("Absen");
        menuAttendances.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAttendancesMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuAttendances);

        menuLogout.setText("Logout");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuLogout);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductsActionPerformed
        ReadProducts products = new ReadProducts();
        products.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuProductsActionPerformed

    private void menuTransactionTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransactionTypesActionPerformed
        if(Session.getRole() != null || Session.getRole().equals("admin")) {
            ReadTransactionTypes transactionTypes = new ReadTransactionTypes();
            transactionTypes.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuTransactionTypesActionPerformed

    private void menuAttendancesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAttendancesMouseClicked
        if(Session.getRole().equals("admin")){
            Today today = new Today();
            today.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");   
        }
    }//GEN-LAST:event_menuAttendancesMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        Session.setId("");
        Session.setName("");
        Login login = new Login();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductsMouseClicked
//        ReadProducts products = new ReadProducts();
//        products.setVisible(true);
//        dispose();
    }//GEN-LAST:event_menuProductsMouseClicked

    private void menuEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmployeesActionPerformed
        if(Session.getRole() != null || Session.getRole().equals("admin")) {
            ReadEmployees employees = new ReadEmployees();
            employees.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuEmployeesActionPerformed

    private void menuTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransactionsActionPerformed
        Transactions.Form trxForm = new Form();
        trxForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuTransactionsActionPerformed

    private void menuEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntriesActionPerformed
        ReadEntries entries = new ReadEntries();
        entries.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuEntriesActionPerformed

    private void menuExitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitsActionPerformed
        ReadExits exits = new ReadExits();
        exits.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuExitsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuAttendances;
    private javax.swing.JMenuItem menuEmployees;
    private javax.swing.JMenuItem menuEntries;
    private javax.swing.JMenuItem menuExits;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenuItem menuProducts;
    private javax.swing.JMenuItem menuTransactionTypes;
    private javax.swing.JMenuItem menuTransactions;
    // End of variables declaration//GEN-END:variables
}
