/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koperasi;

import Attendance.Today;
import Auth.Login;
import Auth.Session;
import Employees.ReadEmployees;
import Entries.ReadEntries;
import Products.ReadProducts;
import Suppliers.ReadSuppliers;
import Categories.ReadCategories;
import Koneksi.Koneksi;
import Reports.Attendance;
import Reports.Entry;
import Reports.Transaction;
import Transactions.Form;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ryans
 */
public class MainMenu extends javax.swing.JFrame {
private Connection conn = new Koneksi().getConnection();

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        if(Session.getRole() == null) {
            JOptionPane.showMessageDialog(null, "Silahkan login terlebih dahulu"); 
            Login login = new Login();
            dispose();
            login.setVisible(true);
        } else {
            initComponents();
            setLocationRelativeTo(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuProducts = new javax.swing.JMenuItem();
        menuEmployees = new javax.swing.JMenuItem();
        menuTransactionTypes = new javax.swing.JMenuItem();
        menuSuppliers = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuTransactions = new javax.swing.JMenuItem();
        menuEntries = new javax.swing.JMenuItem();
        menuAttendances = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuAttendanceReport = new javax.swing.JMenuItem();
        menuTrxReport = new javax.swing.JMenuItem();
        menuEntryReport = new javax.swing.JMenuItem();
        menuStockReport = new javax.swing.JMenuItem();
        menuSupplierReport = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 128, 185));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELAMAT DATANG DI HALAMAN UTAMA");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homepage.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu3.setText("Master");

        menuProducts.setText("Produk");
        menuProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProductsMouseClicked(evt);
            }
        });
        menuProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductsActionPerformed(evt);
            }
        });
        jMenu3.add(menuProducts);

        menuEmployees.setText("Pegawai");
        menuEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmployeesActionPerformed(evt);
            }
        });
        jMenu3.add(menuEmployees);

        menuTransactionTypes.setText("Tipe Transaksi");
        menuTransactionTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransactionTypesActionPerformed(evt);
            }
        });
        jMenu3.add(menuTransactionTypes);

        menuSuppliers.setText("Supplier");
        menuSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSuppliersActionPerformed(evt);
            }
        });
        jMenu3.add(menuSuppliers);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Transaksi");

        menuTransactions.setText("Pembelian");
        menuTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransactionsActionPerformed(evt);
            }
        });
        jMenu4.add(menuTransactions);

        menuEntries.setText("Barang Masuk");
        menuEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntriesActionPerformed(evt);
            }
        });
        jMenu4.add(menuEntries);

        jMenuBar2.add(jMenu4);

        menuAttendances.setText("Absen");
        menuAttendances.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAttendancesMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuAttendances);

        jMenu1.setText("Laporan");

        menuAttendanceReport.setText("Kehadiran");
        menuAttendanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAttendanceReportActionPerformed(evt);
            }
        });
        jMenu1.add(menuAttendanceReport);

        menuTrxReport.setText("Transaksi");
        menuTrxReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrxReportActionPerformed(evt);
            }
        });
        jMenu1.add(menuTrxReport);

        menuEntryReport.setText("Barang Masuk");
        menuEntryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntryReportActionPerformed(evt);
            }
        });
        jMenu1.add(menuEntryReport);

        menuStockReport.setText("Stok Barang");
        menuStockReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStockReportActionPerformed(evt);
            }
        });
        jMenu1.add(menuStockReport);

        menuSupplierReport.setText("Data Supplier");
        menuSupplierReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSupplierReportActionPerformed(evt);
            }
        });
        jMenu1.add(menuSupplierReport);

        jMenuBar2.add(jMenu1);

        menuLogout.setText("Logout");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuLogout);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductsActionPerformed
        ReadProducts products = new ReadProducts();
        products.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuProductsActionPerformed

    private void menuTransactionTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransactionTypesActionPerformed
        if(Session.getRole().equals("admin")) {
            ReadCategories transactionTypes = new ReadCategories();
            transactionTypes.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuTransactionTypesActionPerformed

    private void menuAttendancesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAttendancesMouseClicked
        if(Session.getRole().equals("admin")){
            Today today = new Today();
            today.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");   
        }
    }//GEN-LAST:event_menuAttendancesMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        Session.setId("");
        Session.setName("");
        Login login = new Login();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductsMouseClicked
//        ReadProducts products = new ReadProducts();
//        products.setVisible(true);
//        dispose();
    }//GEN-LAST:event_menuProductsMouseClicked

    private void menuEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmployeesActionPerformed
        if(Session.getRole().equals("admin")) {
            ReadEmployees employees = new ReadEmployees();
            employees.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuEmployeesActionPerformed

    private void menuTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransactionsActionPerformed
        Transactions.Form trxForm = new Form();
        trxForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuTransactionsActionPerformed

    private void menuEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntriesActionPerformed
        ReadEntries entries = new ReadEntries();
        entries.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuEntriesActionPerformed

    private void menuSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSuppliersActionPerformed
        if(Session.getRole().equals("admin")) {
            ReadSuppliers suppliers = new ReadSuppliers();
            suppliers.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuSuppliersActionPerformed

    private void menuAttendanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAttendanceReportActionPerformed
        if(Session.getRole().equals("admin")) {
            Attendance attendance = new Attendance();
            attendance.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuAttendanceReportActionPerformed

    private void menuEntryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntryReportActionPerformed
        if(Session.getRole().equals("admin")) {
            Entry entry = new Entry();
            entry.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuEntryReportActionPerformed

    private void menuTrxReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrxReportActionPerformed
        if(Session.getRole().equals("admin")) {
            Transaction transaction = new Transaction();
            transaction.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuTrxReportActionPerformed

    private void menuStockReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStockReportActionPerformed
        if(Session.getRole().equals("admin")) {
            try {
                String path = "./src/Reports/products_stock_report.jasper";
                HashMap parameter = new HashMap();
                JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
                JasperViewer.viewReport(print, false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Dokumen tidak ada " + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuStockReportActionPerformed

    private void menuSupplierReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSupplierReportActionPerformed
        if(Session.getRole().equals("admin")) {
            try {
                String path = "./src/Reports/suppliers_report.jasper";
                HashMap parameter = new HashMap();
                JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
                JasperViewer.viewReport(print, false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Dokumen tidak ada " + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Akses tidak diizinkan");
        }
    }//GEN-LAST:event_menuSupplierReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAttendanceReport;
    private javax.swing.JMenu menuAttendances;
    private javax.swing.JMenuItem menuEmployees;
    private javax.swing.JMenuItem menuEntries;
    private javax.swing.JMenuItem menuEntryReport;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenuItem menuProducts;
    private javax.swing.JMenuItem menuStockReport;
    private javax.swing.JMenuItem menuSupplierReport;
    private javax.swing.JMenuItem menuSuppliers;
    private javax.swing.JMenuItem menuTransactionTypes;
    private javax.swing.JMenuItem menuTransactions;
    private javax.swing.JMenuItem menuTrxReport;
    // End of variables declaration//GEN-END:variables
}
