/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Transactions;

import Koneksi.Koneksi;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ryans
 */
public class Add extends javax.swing.JFrame {
private Connection conn = new Koneksi().getConnection();
private DefaultTableModel tabmode;
private String product_code = "";

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
        setLocationRelativeTo(this);
        datatable();
    }
 protected void datatable() {
        Object[] Baris = {
            "Kode", 
            "Nama",
            "Harga",
        };
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();
        
        try {
            String sql = "SELECT * FROM products where product_code like '%"+cariitem+"%' or name like '%"+cariitem+"%' order by product_code asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()) {
                tabmode.addRow(new Object[] {
                    hasil.getString("product_code"),
                    hasil.getString("name"),
                    hasil.getString("price"),
                });
            }
            tblTransactions.setModel(tabmode);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblProducts = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        addToCart = new javax.swing.JButton();
        amount = new javax.swing.JTextField();
        productName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransactionsMouseClicked(evt);
            }
        });
        tblProducts.setViewportView(tblTransactions);

        txtcari.setName("txtcari"); // NOI18N

        bcari.setText("Cari");
        bcari.setName("bcari"); // NOI18N
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        addToCart.setText("Tambah ke Keranjang");
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });

        amount.setToolTipText("Jumlah");
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        productName.setText("Nama Produk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bcari))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(productName)
                                .addGap(18, 18, 18)
                                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addToCart)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addGap(18, 18, 18)
                .addComponent(tblProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToCart)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productName))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransactionsMouseClicked
        int row = tblTransactions.rowAtPoint(evt.getPoint());
        int col = tblTransactions.columnAtPoint(evt.getPoint());
        try {
            product_code = (String) tblTransactions.getModel().getValueAt(row, col);
            
            String sqlSearchId = "SELECT name FROM products where product_code = '"+product_code+"'";
            Statement statId = conn.createStatement();
            ResultSet rs = statId.executeQuery(sqlSearchId);
            if(rs.next()) {
               productName.setText(rs.getString("name"));
            } else {
                productName.setText("Error");
            }
        }
        catch(NumberFormatException | SQLException e) {
            product_code = "";
            System.out.println(e);
        }
    }//GEN-LAST:event_tblTransactionsMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        if(product_code != "" && amount.getText() != "" && productName.getText() != "Error") {
//            get last invoice id
            try {
            String sqlLastInvoiceId = "SELECT inv_id FROM transactions order by inv_id desc limit 1";
            Statement statLastInvoiceId = conn.createStatement();
            ResultSet rs = statLastInvoiceId.executeQuery(sqlLastInvoiceId);
            String lastInvoice = "";
            if(rs.next()) {
              lastInvoice = rs.getString("inv_id");
              lastInvoice = lastInvoice.substring(lastInvoice.lastIndexOf("-") + 1);
            }
            
            if(lastInvoice != "") {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyyyy");
                LocalDateTime now = LocalDateTime.now();
                String dateLastOrder = lastInvoice.substring(0, 8);
                // jika ada order di hari yang sama
                int orderToday = 0;
                if(dateLastOrder.equals(dtf.format(now))) {
                    if(lastInvoice.indexOf("0", 9) > 0) {
                        System.out.println("puluhan");
                    } else if(lastInvoice.indexOf("0", 8) > 0) {
                        System.out.println("ratusan");
                    }
                    
//                    orderToday = Integer.valueOf(lastInvoice.substring(lastInvoice.length() - 1));
                }
//                System.out.println(String.format("%03d", orderToday));
                
            }
//            String sql = "insert into transactions values(?,?,?,?,?)";
//            PreparedStatement stat = conn.prepareStatement(sql);
//            stat.setString(1, );
//            stat.setInt(2, typeId);
//            stat.setString(3, name.getText());
//            stat.setString(4, gambar);
//            stat.setString(5, price.getText());
//
//            stat.executeUpdate();
//            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
            }
        }
//        Add add = new Add();
//        add.setVisible(true);
//        dispose();
    }//GEN-LAST:event_addToCartActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCart;
    private javax.swing.JTextField amount;
    private javax.swing.JButton bcari;
    private javax.swing.JLabel productName;
    private javax.swing.JScrollPane tblProducts;
    private javax.swing.JTable tblTransactions;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
